# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Desgard_Duan
tagline:          'Surprise'
description:      'Hello,World!'
url:              http://shelldone.com

author:
  name:           'Desgard_Duan'
  url:            https://github.com/dgytdhy

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : soohu
