permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 6
comments: true
paginate_path: "/page/:num"

baseurl: ""
domain_name: desgard.com
google_analytics: UA-52446115-1
baidu_toongji: 
project_url: http://project.desgard.com
life_url: http://life.desgard.com

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Gua
title: Guardia · 瓜地
description: "瓜地"
meta_description: "iOS Dev. Blog by Desgard_Duan. "
url: http://www.desgard.com
production_url: http://www.desgard.com
repo: https://github.com/desgard
disqus_shortname: "desgard"
rss_path: source/
author:
  name      : Desgard_Duan
  image     : /assets/images/logo-new.png
  email     : gua@desgard.com
  url       : http://www.desgard.com
  facebook  : https://www.facebook.com/desgard.duan
  twitter   : https://twitter.com/Desgard_Duan
  instagram : http://instagram.com/nandomoreira.me
  github    : http://github.com/desgard
  linkedin  : http://linkedin.com/in/nandomoreirame
  sof       : http://stackoverflow.com/users/6119149/desgard-duan
  weibo     : http://weibo.com/desgard
  bio       : "iOS Dev and try to do everything."

# thought
thought:
  text: Have a beginner mind.
  author: Gua

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
