# Dependencies
markdown:         kramdown
kramdown:
    input: GFM
    extensions:
        - autolink
        - footnotes
        - smart
    enable_coderay: true
    syntax_highlighter: rouge
    coderay:
        coderay_line_numbers:  nil
gems:             [jekyll-paginate] 

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Desgard_Duan
tagline:          'Surprise'
description:      ''
url:              http://shelldone.com

author:
  name:           'Desgard_Duan'
  url:            https://github.com/dgytdhy

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : desgard
      

# collection for knowledge
collections:
    knowledge:
        output: true
        path: /knowledge/

